### ISSUE TITLE
Correct name for `$.xgafv` query parameter

### ISSUE THREAD

**Issue by pinalbaldha** [stackql/google-discovery-to-openapi#19]
GCP APIs supports `$.xgafv` as a query parameter: https://cloud.google.com/apis/docs/system-parameters#definitions
While translating Google Discovery spec to OpenAPI spec, it seems there is a logic to replace `$` with `_` because OpenAPI components key regex should match `^[a-zA-Z0-9\.\-_]+$`.

Because of this replacement logic, the query parameter name changed to `_.xgafv`. Instead, it should be `$.xgafv`.

Current doc:
```
components:
  parameters:
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
```

Expected doc:
```
components:
  parameters:
    _.xgafv:
      description: V1 error format.
      in: query
      name: $.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
```
